### ISSUE TITLE
network: Close returns an error on closing connections

### ISSUE THREAD

**Issue by SUMUKHA-PK** [xqueries/xdb#53]
**Describe the bug**
The closing of a connection using `Close` returns an error which is propagated to `cluster.Close`'s.

**To Reproduce**
Tests fail in `raft` branch, refer.

**Expected behaviour**
No error on closing connections.

**Comment by tsatke** [comment]
As far as I understood, @SUMUKHA-PK you added a workaround for this?

Closing in favor of #61

**Comment by SUMUKHA-PK** [comment]
Yup. Perfect
