### ISSUE TITLE
tool: create tool for debugging a database file

### ISSUE THREAD

**Issue by tsatke** [xqueries/xdb#59]
A database file currently is not readable.
To manually inspect the contents of such a file, we want to have a tool to use, which displays information about the file.
We want this tool to be usable as a sub-command of the `xdb` command, such as `xdb debug`.

The developer should figure out, which properties are most important. He should also figure out, which sub-commands to the debug command would make sense to have.
As an example, here are some example commands and outputs.
```
$ xdb debug file.db
Summary of file.db (size 256KiB)
  Pages:  4
  Tables: 1
  Unused: 255KiB
```
```
$ xdb debug tables file.db
Summary of tables in file.db
  Tables: 1
Summary of 'myTable'
  Schema:
    CREATE TABLE myTable (
      id CHAR,
      created DATE
    )
  Records: 1
```
and many more.

**Comment by tsatke** [comment]
Before starting the implementation, please aggregate all interesting properties and discuss with @tsatke first, please.

**Comment by tsatke** [comment]
May be interesting: #65

**Comment by SUMUKHA-PK** [comment]
Merging with #65 and closing this.
