### ISSUE TITLE
inspect: requirements engineering

### ISSUE THREAD

**Issue by tsatke** [xqueries/xdb#66]
Requirements are to be added as notes to the To do column of the Inspector project (https://github.com/xqueries/xdb/projects/4).

**Comment by SUMUKHA-PK** [comment]
General requirements of the tool:
1. The tool must be able to read a DB file and provide the details available via the file in a human friendly format.
2. The CLI is interactive for some commands which enables the CLI to be stateful. Find in depth explanation with specific commands that support this.
3. The commands that are supported will be in the scope of the data available in the DB file and the supporting engine implementation and will be explained in further requirements.
4. Auto-completion - auto completion for table names on `Tab` (or as supported by the CLI library).
4. Command - Help: Gives a basic explanation on how to use the CLI and on specific commands too.
5. Command - Overview: Gives a basic idea of the entire file; data on how much space is used, how many tables exist etc - detail in ticket.
6. Command - page: Usage - `page numberOfPage`. Gives cell level data on the page, detail in ticket.
7. Command - table: Usage - `table TableName`. Display table data as provided by engine.

**Comment by SUMUKHA-PK** [comment]
Adding them to the epic #65 and closing this.
